[project]
name = "ucloud-comfyui"
description = "This is a set of ComfyUI nodes for UCloud Moderlverse Image generation model API."
version = "1.0.0"
license = {file = "LICENSE"}
dependencies = ["requests", "pillow"]

[project.urls]
Repository = "https://github.com/ucloud/ucloud-comfyui"

[tool.comfy]
PublisherId = "khalil-song"
DisplayName = "ucloud-comfyui"
Icon = "https://www-s.ucloud.cn/2025/07/4a29a785049191245cea58d2176157d2_1753185180124.jpg"
includes = []
